#spring:
#  server:
#    port:8080;
spring:
  data:
    mongodb:
      host: localhost
      database: mydb
      port: 27017
      field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy



